name: Auto Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to live site
        shell: cmd
        run: |
          xcopy /y /e templates "C:\inetpub\wwwroot\device_form\templates"
          xcopy /y /e templates "C:\Users\Administrator\Desktop\device_form\templates"
          xcopy /y /e templates "C:\Users\Administrator\device_form\templates"
          copy /y app.py "C:\inetpub\wwwroot\device_form\app.py"
          copy /y app.py "C:\Users\Administrator\Desktop\device_form\app.py"
          copy /y app.py "C:\Users\Administrator\device_form\app.py"

      - name: Restart IIS
        shell: cmd
        run: iisreset /noforce